##################
# Server Config
#################
spring.application.name=kun_uz_practise
server.port=8080
server.domain.name=http://localhost:${server.port}
###################
#### Attach
##################

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

attach.folder.name=attaches
attach.open.url=${server.domain.name}/api/v1/attach/open

###################
#### Database
##################
spring.datasource.url=jdbc:postgresql://localhost:5432/kun_uz_practise
spring.datasource.username=userjon
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
