### article like
POST localhost:8080/api/v1/articleLike/like/1481f488-122c-48de-b458-53c99429495a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mzk3ODQwNTMsImV4cCI6MTczOTg3MDQ1MywiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsInBob25lIjoiKzk5ODkwODA3MDE3NiIsInJvbGUiOiJST0xFX1VTRVIifQ.nuR-D2pcDVUxfIduiNkCza3VM1Ela14va5OzG5hSQmEEzUSGMNPlr6zpyydom6AGQNmbWkO_tSc6QkApkoxb1Q
### article dislike
POST localhost:8080/api/v1/articleLike/dislike/1481f488-122c-48de-b458-53c99429495a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mzk3ODQwNTMsImV4cCI6MTczOTg3MDQ1MywiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsInBob25lIjoiKzk5ODkwODA3MDE3NiIsInJvbGUiOiJST0xFX1VTRVIifQ.nuR-D2pcDVUxfIduiNkCza3VM1Ela14va5OzG5hSQmEEzUSGMNPlr6zpyydom6AGQNmbWkO_tSc6QkApkoxb1Q


