### login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: ru

{
  "phone": "+998908070144",
  "password": "123456"
}

### registration
POST localhost:8080/api/v1/auth/registration/email
Content-Type: application/json

{
  "name": "ss",
  "surname": "Teshmatov",
  "phone": "+998908070188",
  "email": "runnerpro1990@gmail.com",
  "password": "123456"
}
### registration by phone
POST localhost:8080/api/v1/auth/registration/phone
Content-Type: application/json

{
  "name": "Eshmat",
  "surname": "Teshmatov",
  "phone": "+998908070176",
  "email": "runnerpro1990@gmail.com",
  "password": "123456"
}

### verification by Phone
POST localhost:8080/api/v1/auth/verification/phone
Content-Type: application/json

{
  "phone": "+998908070176",
  "code": "36090"
}