### get by email
GET localhost:8080/api/v1/emailHistory/admin?email=runnerpro1990@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzkzNjU3MTcsImV4cCI6MTczOTQ1MjExNywiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsImlkIjoiODEyNzQ0MTEtYjAyZi00N2RhLTk2ZTEtNmQ4ZWVmOGEzNjQxIiwicm9sZSI6IkFETUlOIn0.A5o1TR6PEvpXpZJsNqQDagdorJsN1xav9lc7ipZB0T5lM_JTsook0j0UeZyDRLA4zAt130rYXszXBOFJHozWSw

### get by Date between pagination
GET localhost:8080/api/v1/emailHistory/admin/getByDate?page=1&size=10&from=2025-02-01&to=2025-02-20
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MzkzNjU3MTcsImV4cCI6MTczOTQ1MjExNywiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsImlkIjoiODEyNzQ0MTEtYjAyZi00N2RhLTk2ZTEtNmQ4ZWVmOGEzNjQxIiwicm9sZSI6IkFETUlOIn0.A5o1TR6PEvpXpZJsNqQDagdorJsN1xav9lc7ipZB0T5lM_JTsook0j0UeZyDRLA4zAt130rYXszXBOFJHozWSw