### save article
POST localhost:8080/api/v1/savedArticle/1c982ce0-535d-4e85-b3f2-e332a24cad51
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mzk3ODQwNTMsImV4cCI6MTczOTg3MDQ1MywiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsInBob25lIjoiKzk5ODkwODA3MDE3NiIsInJvbGUiOiJST0xFX1VTRVIifQ.nuR-D2pcDVUxfIduiNkCza3VM1Ela14va5OzG5hSQmEEzUSGMNPlr6zpyydom6AGQNmbWkO_tSc6QkApkoxb1Q
### get by profileId
GET localhost:8080/api/v1/savedArticle
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mzk3ODQwNTMsImV4cCI6MTczOTg3MDQ1MywiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsInBob25lIjoiKzk5ODkwODA3MDE3NiIsInJvbGUiOiJST0xFX1VTRVIifQ.nuR-D2pcDVUxfIduiNkCza3VM1Ela14va5OzG5hSQmEEzUSGMNPlr6zpyydom6AGQNmbWkO_tSc6QkApkoxb1Q
