### get history by Phone
GET localhost:8080/api/v1/smsHistory/admin/+998908070176
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mzk0MzcxNjAsImV4cCI6MTczOTUyMzU2MCwiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsImlkIjoiODEyNzQ0MTEtYjAyZi00N2RhLTk2ZTEtNmQ4ZWVmOGEzNjQxIiwicm9sZSI6IkFETUlOIn0.GaZHtJ9oy3ZYzArKl6lGr1ahu01Uj85L0UgOyPnvNSZl3mXHvQUosV-Nn6__TZfRV3al3CU3BgYVM_fhKeEKIQ
### get history by Date
GET localhost:8080/api/v1/smsHistory/admin/getByDate?from=2025-02-10&to=2025-02-23&page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mzk0MzcxNjAsImV4cCI6MTczOTUyMzU2MCwiaXNzIjoiS3VuIHV6IHRlc3QgcG9ydGFsaSIsImlkIjoiODEyNzQ0MTEtYjAyZi00N2RhLTk2ZTEtNmQ4ZWVmOGEzNjQxIiwicm9sZSI6IkFETUlOIn0.GaZHtJ9oy3ZYzArKl6lGr1ahu01Uj85L0UgOyPnvNSZl3mXHvQUosV-Nn6__TZfRV3al3CU3BgYVM_fhKeEKIQ